apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  labels:
    app: nginx-gitops

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-gitops

  template:
    metadata:
      labels:
        app: nginx-gitops

    spec:
      volumes:
      - name: html
        configMap:
          name: nginx-html

      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80

        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
